DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

DROP TABLE IF EXISTS search_history;

CREATE TABLE search_history
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    city TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);